#!/usr/bin/env bash

set -ex

function pack {
    local package_name dir_name
    package_name="$PROJECT_NAME-$TRAVIS_TAG-$TARGET"
    dir_name="target/$TARGET/release"

    strip "$dir_name/$PROJECT_NAME"
    tar -C "$dir_name" -cvzf "$package_name.tar.gz" "$PROJECT_NAME"
}

cargo build --target "$TARGET" --release --verbose
pack
